export { default as VisitPanel } from "./VisitPanel";
export { default as Statistics } from "./statistics";
export { default as Investors } from "./Investors";
export { default as Business } from "./Business";
export { default as NavBar } from "./NavBar";
export { default as Footer } from "./Footer";
export { default as Offers } from "./Offers";
export { default as About } from "./About";
export { default as ContactPanel } from "./ContactPanel";
